### PR TITLE
based on https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Man…

### PR DESCRIPTION
**Pull request by 877509395**
…ual-%28v2.x%29#t

t:none should be add before every transformation.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for fixing this.

We usually write all the transformations (-> `t:...`) on the same line. Would you mind adopting your PR? If not, I can do this for you.

**Comment by 877509395** [comment]
yes, i will update.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coreruleset/auto-decoding-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coreruleset/auto-decoding-plugin] based on https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Man… (PR #1)





 
Thank you for fixing this.
 
We usually write all the transformations (-&gt; t:...) on the same line. Would you mind adopting your PR? If not, I can do this for you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dune73** [comment]
Thank you

**Comment by dune73** [comment]
Thank you for this welcome contribution. Merging now.

**Comment by 877509395** [comment]
1

**Pull request merged**
